### ISSUE TITLE
FS#21453 - Make static /etc/resolv.conf configurable via RESOLV_CONF

### ISSUE THREAD

**Issue by maandree** [GNU-Pony/netcfg#20]
https://bugs.archlinux.org/task/21453?project=1&string=netcfg&status=&pagenum=1&order=lastedit&sort=desc

**Comment by maandree** [comment]
patch does not apply

**Comment by fluxer** [comment]
It patches the docs too, which you have changed to info files. Remove the hunks applying changes to the docs and then try applying the patch. You may have to manually adjust the docs but I guess you can deal with that.

**Comment by maandree** [comment]
I have tried to apply it to older versions, but I cannot find any that is applies to. So it may require some manual work.

**Comment by maandree** [comment]
I have tried with only the src patch.

**Comment by fluxer** [comment]
I will see what I can do about it later.

**Comment by fluxer** [comment]
Here is a patch: http://pastebin.com/zXH7XH2y. However, from the origin patch from the bug report DNS1 and DNS2 were deprecated by the time the bug was reported. I don't know where did you imported the sources from and were DNS1 and DNS2 implemented later on or removed in the sources you used so there is a hunk I didn't bothered with. I applied only what is relevant to the current sources.

**Comment by maandree** [comment]
Next time you can create a patch file with `git format-patch origin/master`, then the patch file
also contains individual commits with there own commit message, date, and author.
That is just if you want your name in the log, otherwise it does not matter to me.

**Comment by fluxer** [comment]
I'm not worried about the credits so it's not a problem for me either but I will have the command suggested in mind next time I do this.

**Comment by maandree** [comment]
I figured not, so I did not hand craft it in there. Just wanted to let you know how to do this incase you did not know.
But for patches with multiple logical changes, it is nice to do some.

**Comment by maandree** [comment]
Thinking of it, it is a bit weird that git commands for collaborating is not documented under `git help`.

**Comment by fluxer** [comment]
Yep, kind of weird. I guess `git format-patch` is supposed to be used by internal tools only and if one wants to get a patch from commit use `git diff <blob> <blob> > <file>` or just `git diff > <file>` (which is what I used). There is man page for `git format-patch` tough.

**Comment by maandree** [comment]
It is listed under ancillary commands in `man  git`, but not under main porcelain commands. But it under high-level, so you are suppost to run it manually.
